# Rename this file to languages.toml to enable multilingual support
[zh-cn]
contentDir = "content/zh"
languageName = "中文"
languagedirection = "ltr"
title = "maybemia"
weight = 1
[en]
contentDir = "content/en"
languageName = "English"
languagedirection = "ltr"
title = "Maybemia"
weight = 2